#!/usr/bin/env python3
"""Generate an input script that visits every clickable zone of the main menu.

The menu keeps the pointer at (JOY0DAT counts / 2); zones are compared in hires
x (= counts) and lowres y (= counts / 2). Output: port/tests/data/menu_tour.txt
"""
import sys

ZONES = [  # (x1, x2, y1, y2, name) from the table at $1B422
    (293, 308, 114, 127, 'positions up'), (293, 308, 145, 158, 'positions down'),
    (109, 176, 166, 175, 'player up'), (109, 176, 209, 218, 'player down'),
    (324, 544, 165, 176, 'level list up'), (324, 544, 208, 219, 'level list down'),
    (110, 121, 39, 44, 'new player'), (110, 121, 49, 54, 'delete player'),
    (110, 121, 59, 64, 'skip level'), (110, 121, 69, 74, 'statistics'),
    (538, 548, 146, 151, 'zone 10'), (240, 262, 173, 184, 'ok'),
    (110, 121, 79, 84, 'gfx tutor'), (110, 121, 89, 94, 'demo'), (210, 295, 195, 219, '1/2 players'),
]
# Amiga raw key codes for letters
KEYS = {'A': 0x20, 'B': 0x35, 'C': 0x33, 'D': 0x22, 'E': 0x12, 'S': 0x21, 'T': 0x14, 'Z': 0x31, 'RETURN': 0x44, 'BS': 0x41}


class Script:
    def __init__(self, start):
        self.f = start
        self.cx = 0   # mouse counts
        self.cy = 0
        self.lines = []

    def add(self, s):
        self.lines.append('%d %s' % (self.f, s))

    def move_to(self, hx, y):
        tx, ty = hx, 2 * y
        while self.cx != tx or self.cy != ty:
            dx = max(-100, min(100, tx - self.cx))
            dy = max(-100, min(100, ty - self.cy))
            self.add('mouse %d %d 0 0' % (dx, dy))
            self.cx += dx
            self.cy += dy
            self.f += 2

    def click(self, hold=4, after=60):
        self.add('mouse 0 0 1 0')
        self.f += hold
        self.add('mouse 0 0 0 0')
        self.f += after

    def key(self, name, after=6):
        self.add('key %d 1' % KEYS[name])
        self.f += 3
        self.add('key %d 0' % KEYS[name])
        self.f += after

    def zone(self, i, after=60):
        x1, x2, y1, y2, _ = ZONES[i]
        self.move_to((x1 + x2) // 2, (y1 + y2) // 2)
        self.lines.append('# zone %d: %s' % (i, ZONES[i][4]))
        self.click(after=after)

    def fire(self, after=10):
        self.add('joy F')
        self.f += 4
        self.add('joy -')
        self.f += after


def main():
    s = Script(700)
    # scroll the lists
    for i in (0, 1, 1, 0, 2, 3, 3, 2, 4, 5, 5, 4):
        s.zone(i, after=30)
    s.zone(9, after=150)        # statistics
    s.click(after=80)           # leave the statistics screen
    s.zone(12, after=150)       # gfx tutor
    for _ in range(4):
        s.click(after=80)
    s.zone(6, after=60)         # new player: type a name
    for k in ('T', 'E', 'S', 'T', 'BS', 'Z', 'RETURN'):
        s.key(k)
    s.f += 60
    s.zone(2, after=30)
    s.zone(11, after=60)        # ok
    s.zone(8, after=100)        # skip level
    s.click(after=80)
    s.zone(10, after=60)
    s.zone(14, after=60)        # 1/2 players
    s.zone(14, after=60)
    s.zone(13, after=2500)      # demo
    s.fire(after=200)
    s.click(after=200)
    s.zone(7, after=100)        # delete player
    s.click(after=100)
    s.fire(after=600)           # start the selected level
    s.lines.append('# end %d' % s.f)
    out = sys.argv[1] if len(sys.argv) > 1 else 'port/tests/data/menu_tour.txt'
    open(out, 'w').write('# generated by tools/gen_menu_tour.py\n' + '\n'.join(s.lines) + '\n')
    print(out, 'frames:', s.f)


if __name__ == '__main__':
    main()
