#!/usr/bin/env python3
"""Generate the bitmap font of the level editor (port/src/editor/font_data.hpp)
from DejaVu Sans Mono (Bitstream Vera / DejaVu license: free to embed).

usage: gen_editor_font.py [path/to/DejaVuSansMono.ttf]
"""
import sys
from PIL import Image, ImageDraw, ImageFont

TTF = sys.argv[1] if len(sys.argv) > 1 else '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'
W, H, SIZE = 8, 16, 13
chars = [chr(c) for c in range(32, 127)]
chars += [chr(c) for c in range(0x410, 0x450)] + ['Ё', 'ё', '№']
chars += list('→←↑↓•…—–−«»×±·▶▼✓↶↷✚●▲↕↔☀☾')

font = ImageFont.truetype(TTF, SIZE)
asc, desc = font.getmetrics()
out = []
for ch in chars:
    img = Image.new('L', (W, H), 0)
    d = ImageDraw.Draw(img)
    bbox = font.getbbox(ch)
    w = font.getlength(ch)
    x = (W - w) / 2
    d.text((x, (H - (asc + desc)) // 2 + 1), ch, font=font, fill=255)
    out.append((ord(ch), list(img.tobytes())))

with open('port/src/editor/font_data.hpp', 'w') as f:
    f.write('// Generated by tools/gen_editor_font.py from DejaVu Sans Mono\n')
    f.write('// (Bitstream Vera / DejaVu fonts license). 8x16 alpha glyphs.\n')
    f.write('#pragma once\n#include <cstdint>\n\nnamespace editor {\n\n')
    f.write('constexpr int kGlyphW = %d, kGlyphH = %d, kGlyphCount = %d;\n' % (W, H, len(out)))
    f.write('const uint32_t kGlyphCodes[kGlyphCount] = {\n')
    for i in range(0, len(out), 12):
        f.write('    ' + ', '.join('0x%04X' % c for c, _ in out[i:i + 12]) + ',\n')
    f.write('};\n\nconst uint8_t kGlyphAlpha[kGlyphCount][kGlyphW * kGlyphH] = {\n')
    for c, px in out:
        f.write('    {' + ','.join(str(v) for v in px) + '},\n')
    f.write('};\n\n}  // namespace editor\n')
print(len(out), 'glyphs')
