#!/usr/bin/env python3
"""Program icons from the game's own tile graphics.

    supaplex.exe        : Murphy (cell code 3)
    supaplex_editor.exe : the terminal (cell code 19)

The 16x16 tiles are scaled by whole numbers (nearest neighbour) to every icon
size, so they stay sharp. Writes
    port/res/supaplex.ico, port/res/supaplex_editor.ico   (Windows resources)
    port/src/platform/icon_data.hpp                       (window icons, 64x64 ARGB)

usage: make_icons.py [data folder, default: data]
"""
import io
import struct
import sys

from PIL import Image

DATA = sys.argv[1] if len(sys.argv) > 1 else 'data'
SIZES = [16, 24, 32, 48, 64, 128, 256]
ICONS = {'supaplex': 3, 'supaplex_editor': 19}


def tiles():
    main = open(DATA + '/MAIN.BIN', 'rb').read()
    gfx = open(DATA + '/GRAPHICS.BIN', 'rb').read()
    be = lambda d, o: int.from_bytes(d[o:o + 4], 'big')
    o = 0x1B5A0 - 0x7E00          # resource pointer table in MAIN.BIN (see editor/gfx.cpp)
    t = be(main, o) + be(main, o + 4)
    pal = t + be(main, o + 8)
    t -= 0x1EE00                  # GRAPHICS.BIN is loaded at $1EE00
    pal -= 0x1EE00
    rgb = []
    for i in range(16):
        v = gfx[pal + 2 * i] << 8 | gfx[pal + 2 * i + 1]
        rgb.append((((v >> 8) & 15) * 17, ((v >> 4) & 15) * 17, (v & 15) * 17))
    plane = 40 * 244

    def tile(code, transparent0):
        x0, y0 = (code % 20) * 16, (code // 20) * 16
        im = Image.new('RGBA', (16, 16))
        for y in range(16):
            for x in range(16):
                base = t + (y0 + y) * 40 + (x0 + x) // 8
                c = 0
                for p in range(4):
                    if gfx[base + p * plane] & (0x80 >> ((x0 + x) & 7)):
                        c |= 1 << p
                im.putpixel((x, y), (0, 0, 0, 0) if transparent0 and c == 0 else rgb[c] + (255,))
        return im
    return tile


def scaled(im, size):
    # whole-number scale, centred (24 = 16 x 1.5 is not whole: 16 on 24 would
    # look lost, 32 cropped is worse; use the 16 scaled by 1 and centred)
    n = max(1, size // 16)
    big = im.resize((16 * n, 16 * n), Image.NEAREST)
    out = Image.new('RGBA', (size, size))
    out.alpha_composite(big, ((size - big.width) // 2, (size - big.height) // 2))
    return out


def write_ico(path, im):
    pngs = []
    for s in SIZES:
        b = io.BytesIO()
        scaled(im, s).save(b, 'PNG')
        pngs.append((s, b.getvalue()))
    head = struct.pack('<HHH', 0, 1, len(pngs))
    offset = 6 + 16 * len(pngs)
    entries, blobs = b'', b''
    for s, data in pngs:
        entries += struct.pack('<BBBBHHII', s % 256, s % 256, 0, 0, 1, 32, len(data), offset)
        offset += len(data)
        blobs += data
    open(path, 'wb').write(head + entries + blobs)


def main():
    tile = tiles()
    header = ['// Generated by tools/make_icons.py from the game graphics: window icons,',
              '// 64x64 ARGB8888 (Murphy for the game, the terminal for the editor).',
              '#pragma once', '#include <cstdint>', '']
    for name, code in ICONS.items():
        # Murphy has a black background in the tile: keep it round (colour 0
        # transparent); the terminal is square and fills its tile
        im = tile(code, transparent0=(code == 3))
        write_ico('port/res/%s.ico' % name, im)
        big = scaled(im, 64)
        raw = big.tobytes()
        px = [raw[i + 3] << 24 | raw[i] << 16 | raw[i + 1] << 8 | raw[i + 2] for i in range(0, len(raw), 4)]
        header.append('const uint32_t kIcon_%s[64 * 64] = {' % name)
        for i in range(0, len(px), 8):
            header.append('    ' + ', '.join('0x%08X' % v for v in px[i:i + 8]) + ',')
        header.append('};')
        header.append('')
    open('port/src/platform/icon_data.hpp', 'w').write('\n'.join(header))
    print('icons written')


if __name__ == '__main__':
    main()
